version: '3.8'

networks:
  99techdb:
    driver: ${APP_NETWORK_DRIVER}
volumes:
  mysql:
    driver: ${APP_VOLUME_DRIVER}

services:
  mysql:
    platform: ${PLATFORM}
    container_name: ${MYSQL_CONTAINER_NAME}
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_DB_PORT}:3306"
    networks:
      - 99techdb
  postgres:
    platform: ${PLATFORM}
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    image: postgres:${POSTGRESQL_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ${POSTGRESQL_DATA_PATH_HOST}:/data/postgres
    ports:
      - "${POSTGRESQL_PORT}:5432"
    networks:
      - 99techdb