version: '3.8'

networks:
  ptechdb:
    driver: ${APP_NETWORK_DRIVER}
volumes:
  mysql:
    driver: ${APP_VOLUME_DRIVER}

services:
  mysql:
    platform: ${PLATFORM}
    container_name: ${MYSQL_CONTAINER_NAME}
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_DB_PORT}:3306"
    networks:
      - ptechdb
  mariadb:
    platform: ${PLATFORM}
    container_name: ${MARIADB_CONTAINER_NAME}
    build:
      context: ./mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
    environment:
      - MYSQL_DATABASE=${MARIADB_DB_NAME}
      - MYSQL_USER=${MARIADB_USERNAME}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${MARIADB_DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_DB_PORT}:3306"
    networks:
      - ptechdb
  postgres:
    platform: ${PLATFORM}
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    build:
      context: ./postgres
      args:
        - VERSION=${POSTGRESQL_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ${POSTGRESQL_DATA_PATH_HOST}/postgres:/data/postgres
      - ${POSTGRESQL_PATH_HOST}/postgres.conf:/data/postgres/postgresql.conf
    ports:
      - "${POSTGRESQL_PORT}:5432"
    networks:
      - ptechdb
  mongo:
    platform: ${PLATFORM}
    build: ./mongodb
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - ${MONGODB_DATA_PATH_HOST}/mongo:/data/db
      - ${MONGODB_DATA_PATH_HOST}/mongo_config:/data/configdb
    networks:
      - ptechdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongo:27017/${MONGODB_ROOT_USERNAME}
    networks:
      - ptechdb
